# Stage 1 — build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_N8N_BASE_URL
ARG VITE_N8N_API_KEY
ARG VITE_UNSUBSCRIBE_SECRET
ARG VITE_BREVO_API_KEY
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_N8N_BASE_URL=$VITE_N8N_BASE_URL
ENV VITE_N8N_API_KEY=$VITE_N8N_API_KEY
ENV VITE_UNSUBSCRIBE_SECRET=$VITE_UNSUBSCRIBE_SECRET
ENV VITE_BREVO_API_KEY=$VITE_BREVO_API_KEY
RUN npm run build

# Stage 2 — serve
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
